# Generated by Django 2.0.6 on 2018-06-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisdoci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
